//
//  Heart.swift
//  GB_iOS_UI_Course
//
//  Created by Alexander Lezin on 26/05/2019.
//  Copyright © 2019 Alexander Lezin. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//



import UIKit

public class Heart : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawCanvas1(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 160, height: 201), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 160, height: 201), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 160, y: resizedFrame.height / 201)


        //// Color Declarations
        let fillColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Group
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 144.77, y: 80.56))
        bezierPath.addCurve(to: CGPoint(x: 115.86, y: 48.85), controlPoint1: CGPoint(x: 136.55, y: 65.87), controlPoint2: CGPoint(x: 127.01, y: 55.38))
        bezierPath.addCurve(to: CGPoint(x: 104.16, y: 32.86), controlPoint1: CGPoint(x: 115.14, y: 47.43), controlPoint2: CGPoint(x: 111.48, y: 40.54))
        bezierPath.addCurve(to: CGPoint(x: 92.53, y: 22.68), controlPoint1: CGPoint(x: 101.19, y: 29.74), controlPoint2: CGPoint(x: 97.33, y: 26.18))
        bezierPath.addCurve(to: CGPoint(x: 107.85, y: 15.08), controlPoint1: CGPoint(x: 100.1, y: 18.07), controlPoint2: CGPoint(x: 107.77, y: 15.11))
        bezierPath.addCurve(to: CGPoint(x: 108.85, y: 14.11), controlPoint1: CGPoint(x: 108.3, y: 14.91), controlPoint2: CGPoint(x: 108.66, y: 14.56))
        bezierPath.addCurve(to: CGPoint(x: 108.83, y: 12.73), controlPoint1: CGPoint(x: 109.03, y: 13.67), controlPoint2: CGPoint(x: 109.03, y: 13.17))
        bezierPath.addCurve(to: CGPoint(x: 98.74, y: 0.24), controlPoint1: CGPoint(x: 104.9, y: 3.9), controlPoint2: CGPoint(x: 98.99, y: 0.38))
        bezierPath.addCurve(to: CGPoint(x: 97.31, y: 0.09), controlPoint1: CGPoint(x: 98.3, y: -0.01), controlPoint2: CGPoint(x: 97.78, y: -0.07))
        bezierPath.addCurve(to: CGPoint(x: 73.17, y: 11.93), controlPoint1: CGPoint(x: 87.97, y: 3.12), controlPoint2: CGPoint(x: 79.86, y: 7.11))
        bezierPath.addCurve(to: CGPoint(x: 64.61, y: 8.95), controlPoint1: CGPoint(x: 70.47, y: 10.84), controlPoint2: CGPoint(x: 67.62, y: 9.84))
        bezierPath.addCurve(to: CGPoint(x: 63.53, y: 8.98), controlPoint1: CGPoint(x: 64.26, y: 8.85), controlPoint2: CGPoint(x: 63.88, y: 8.86))
        bezierPath.addCurve(to: CGPoint(x: 52.06, y: 24.03), controlPoint1: CGPoint(x: 63.11, y: 9.13), controlPoint2: CGPoint(x: 53.08, y: 12.75))
        bezierPath.addCurve(to: CGPoint(x: 53.24, y: 25.85), controlPoint1: CGPoint(x: 51.98, y: 24.84), controlPoint2: CGPoint(x: 52.47, y: 25.59))
        bezierPath.addCurve(to: CGPoint(x: 58.08, y: 27.74), controlPoint1: CGPoint(x: 53.3, y: 25.87), controlPoint2: CGPoint(x: 55.19, y: 26.52))
        bezierPath.addCurve(to: CGPoint(x: 52.05, y: 44.7), controlPoint1: CGPoint(x: 52.37, y: 36.95), controlPoint2: CGPoint(x: 52.06, y: 44.38))
        bezierPath.addCurve(to: CGPoint(x: 52.11, y: 45.2), controlPoint1: CGPoint(x: 52.05, y: 44.87), controlPoint2: CGPoint(x: 52.07, y: 45.04))
        bezierPath.addCurve(to: CGPoint(x: 43.18, y: 47.63), controlPoint1: CGPoint(x: 49.25, y: 45.92), controlPoint2: CGPoint(x: 46.28, y: 46.73))
        bezierPath.addCurve(to: CGPoint(x: 24.64, y: 56.61), controlPoint1: CGPoint(x: 35.87, y: 49.76), controlPoint2: CGPoint(x: 30.33, y: 52.77))
        bezierPath.addCurve(to: CGPoint(x: 26.95, y: 20.33), controlPoint1: CGPoint(x: 23.14, y: 39.72), controlPoint2: CGPoint(x: 26.9, y: 20.57))
        bezierPath.addCurve(to: CGPoint(x: 26.48, y: 18.76), controlPoint1: CGPoint(x: 27.06, y: 19.76), controlPoint2: CGPoint(x: 26.89, y: 19.17))
        bezierPath.addCurve(to: CGPoint(x: 24.92, y: 18.26), controlPoint1: CGPoint(x: 26.07, y: 18.34), controlPoint2: CGPoint(x: 25.49, y: 18.16))
        bezierPath.addLine(to: CGPoint(x: 6.64, y: 21.53))
        bezierPath.addCurve(to: CGPoint(x: 5.22, y: 22.97), controlPoint1: CGPoint(x: 5.91, y: 21.66), controlPoint2: CGPoint(x: 5.34, y: 22.24))
        bezierPath.addCurve(to: CGPoint(x: 5.76, y: 74.84), controlPoint1: CGPoint(x: 1.05, y: 48.5), controlPoint2: CGPoint(x: 3.21, y: 65.26))
        bezierPath.addCurve(to: CGPoint(x: 8.37, y: 127.48), controlPoint1: CGPoint(x: -2.86, y: 90.32), controlPoint2: CGPoint(x: -1.91, y: 109.5))
        bezierPath.addCurve(to: CGPoint(x: 64.46, y: 184.87), controlPoint1: CGPoint(x: 21.13, y: 149.8), controlPoint2: CGPoint(x: 42.1, y: 171.25))
        bezierPath.addCurve(to: CGPoint(x: 101.71, y: 199.7), controlPoint1: CGPoint(x: 76.98, y: 192.49), controlPoint2: CGPoint(x: 89.51, y: 197.48))
        bezierPath.addCurve(to: CGPoint(x: 115.83, y: 201.01), controlPoint1: CGPoint(x: 106.51, y: 200.58), controlPoint2: CGPoint(x: 111.22, y: 201.01))
        bezierPath.addCurve(to: CGPoint(x: 140, y: 196.64), controlPoint1: CGPoint(x: 124.27, y: 201.01), controlPoint2: CGPoint(x: 132.35, y: 199.55))
        bezierPath.addCurve(to: CGPoint(x: 155.25, y: 178.34), controlPoint1: CGPoint(x: 146.62, y: 194.11), controlPoint2: CGPoint(x: 151.75, y: 187.96))
        bezierPath.addCurve(to: CGPoint(x: 144.77, y: 80.56), controlPoint1: CGPoint(x: 164.7, y: 152.41), controlPoint2: CGPoint(x: 159.9, y: 107.63))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 97.58, y: 3.69))
        bezierPath.addCurve(to: CGPoint(x: 104.83, y: 12.52), controlPoint1: CGPoint(x: 98.92, y: 4.68), controlPoint2: CGPoint(x: 102.19, y: 7.43))
        bezierPath.addCurve(to: CGPoint(x: 89.4, y: 20.5), controlPoint1: CGPoint(x: 101.84, y: 13.77), controlPoint2: CGPoint(x: 95.53, y: 16.6))
        bezierPath.addCurve(to: CGPoint(x: 76.96, y: 13.56), controlPoint1: CGPoint(x: 85.73, y: 18.05), controlPoint2: CGPoint(x: 81.59, y: 15.68))
        bezierPath.addCurve(to: CGPoint(x: 97.58, y: 3.69), controlPoint1: CGPoint(x: 82.81, y: 9.63), controlPoint2: CGPoint(x: 89.73, y: 6.32))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 64.2, y: 12.49))
        bezierPath.addCurve(to: CGPoint(x: 96.82, y: 30.65), controlPoint1: CGPoint(x: 78.8, y: 16.89), controlPoint2: CGPoint(x: 89.52, y: 24.15))
        bezierPath.addLine(to: CGPoint(x: 86.82, y: 30.65))
        bezierPath.addCurve(to: CGPoint(x: 85.07, y: 32.4), controlPoint1: CGPoint(x: 85.85, y: 30.65), controlPoint2: CGPoint(x: 85.07, y: 31.43))
        bezierPath.addCurve(to: CGPoint(x: 86.82, y: 34.15), controlPoint1: CGPoint(x: 85.07, y: 33.37), controlPoint2: CGPoint(x: 85.85, y: 34.15))
        bezierPath.addLine(to: CGPoint(x: 100.52, y: 34.15))
        bezierPath.addCurve(to: CGPoint(x: 101.51, y: 35.17), controlPoint1: CGPoint(x: 100.86, y: 34.5), controlPoint2: CGPoint(x: 101.2, y: 34.84))
        bezierPath.addCurve(to: CGPoint(x: 110.12, y: 45.91), controlPoint1: CGPoint(x: 105.49, y: 39.32), controlPoint2: CGPoint(x: 108.31, y: 43.16))
        bezierPath.addCurve(to: CGPoint(x: 99.34, y: 42.33), controlPoint1: CGPoint(x: 106.68, y: 44.38), controlPoint2: CGPoint(x: 103.09, y: 43.18))
        bezierPath.addCurve(to: CGPoint(x: 85.43, y: 40.64), controlPoint1: CGPoint(x: 94.92, y: 41.32), controlPoint2: CGPoint(x: 90.34, y: 40.75))
        bezierPath.addCurve(to: CGPoint(x: 55.74, y: 23.02), controlPoint1: CGPoint(x: 75.64, y: 30.92), controlPoint2: CGPoint(x: 60.38, y: 24.75))
        bezierPath.addCurve(to: CGPoint(x: 64.2, y: 12.49), controlPoint1: CGPoint(x: 56.97, y: 16.17), controlPoint2: CGPoint(x: 62.5, y: 13.24))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 77.96, y: 40.79))
        bezierPath.addCurve(to: CGPoint(x: 77.87, y: 38.76), controlPoint1: CGPoint(x: 77.84, y: 40.12), controlPoint2: CGPoint(x: 77.81, y: 39.44))
        bezierPath.addCurve(to: CGPoint(x: 80.27, y: 40.68), controlPoint1: CGPoint(x: 78.69, y: 39.38), controlPoint2: CGPoint(x: 79.49, y: 40.02))
        bezierPath.addCurve(to: CGPoint(x: 77.96, y: 40.79), controlPoint1: CGPoint(x: 79.51, y: 40.71), controlPoint2: CGPoint(x: 78.74, y: 40.75))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 61.33, y: 29.17))
        bezierPath.addCurve(to: CGPoint(x: 74.7, y: 36.51), controlPoint1: CGPoint(x: 65.25, y: 30.96), controlPoint2: CGPoint(x: 70.09, y: 33.44))
        bezierPath.addCurve(to: CGPoint(x: 74.44, y: 41.08), controlPoint1: CGPoint(x: 74.31, y: 38.05), controlPoint2: CGPoint(x: 74.22, y: 39.58))
        bezierPath.addCurve(to: CGPoint(x: 55.6, y: 44.35), controlPoint1: CGPoint(x: 68.7, y: 41.65), controlPoint2: CGPoint(x: 62.47, y: 42.73))
        bezierPath.addCurve(to: CGPoint(x: 61.33, y: 29.17), controlPoint1: CGPoint(x: 55.77, y: 42.65), controlPoint2: CGPoint(x: 56.66, y: 36.52))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 23.04, y: 22.16))
        bezierPath.addCurve(to: CGPoint(x: 23.42, y: 69.17), controlPoint1: CGPoint(x: 21.73, y: 29.85), controlPoint2: CGPoint(x: 18.41, y: 53.21))
        bezierPath.addCurve(to: CGPoint(x: 12.15, y: 82.14), controlPoint1: CGPoint(x: 22.97, y: 71.28), controlPoint2: CGPoint(x: 20.52, y: 80.71))
        bezierPath.addCurve(to: CGPoint(x: 6.81, y: 39.21), controlPoint1: CGPoint(x: 10.41, y: 78.6), controlPoint2: CGPoint(x: 4.92, y: 65.14))
        bezierPath.addLine(to: CGPoint(x: 16.33, y: 39.21))
        bezierPath.addCurve(to: CGPoint(x: 18.09, y: 37.46), controlPoint1: CGPoint(x: 17.3, y: 39.21), controlPoint2: CGPoint(x: 18.09, y: 38.43))
        bezierPath.addCurve(to: CGPoint(x: 16.33, y: 35.7), controlPoint1: CGPoint(x: 18.09, y: 36.49), controlPoint2: CGPoint(x: 17.3, y: 35.7))
        bezierPath.addLine(to: CGPoint(x: 7.11, y: 35.7))
        bezierPath.addCurve(to: CGPoint(x: 8.49, y: 24.76), controlPoint1: CGPoint(x: 7.43, y: 32.26), controlPoint2: CGPoint(x: 7.89, y: 28.62))
        bezierPath.addLine(to: CGPoint(x: 23.04, y: 22.16))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 6, y: 113.52))
        bezierPath.addLine(to: CGPoint(x: 18.86, y: 113.52))
        bezierPath.addCurve(to: CGPoint(x: 20.62, y: 111.77), controlPoint1: CGPoint(x: 19.84, y: 113.52), controlPoint2: CGPoint(x: 20.62, y: 112.74))
        bezierPath.addCurve(to: CGPoint(x: 18.86, y: 110.01), controlPoint1: CGPoint(x: 20.62, y: 110.8), controlPoint2: CGPoint(x: 19.84, y: 110.01))
        bezierPath.addLine(to: CGPoint(x: 5, y: 110.01))
        bezierPath.addCurve(to: CGPoint(x: 3.65, y: 102.14), controlPoint1: CGPoint(x: 4.34, y: 107.37), controlPoint2: CGPoint(x: 3.89, y: 104.74))
        bezierPath.addLine(to: CGPoint(x: 37.41, y: 102.14))
        bezierPath.addCurve(to: CGPoint(x: 39.17, y: 100.39), controlPoint1: CGPoint(x: 38.38, y: 102.14), controlPoint2: CGPoint(x: 39.17, y: 101.35))
        bezierPath.addCurve(to: CGPoint(x: 37.41, y: 98.63), controlPoint1: CGPoint(x: 39.17, y: 99.42), controlPoint2: CGPoint(x: 38.38, y: 98.63))
        bezierPath.addLine(to: CGPoint(x: 3.45, y: 98.63))
        bezierPath.addCurve(to: CGPoint(x: 7.27, y: 79.66), controlPoint1: CGPoint(x: 3.32, y: 91.99), controlPoint2: CGPoint(x: 4.59, y: 85.57))
        bezierPath.addCurve(to: CGPoint(x: 9.68, y: 84.96), controlPoint1: CGPoint(x: 8.5, y: 83.04), controlPoint2: CGPoint(x: 9.55, y: 84.74))
        bezierPath.addCurve(to: CGPoint(x: 11.17, y: 85.78), controlPoint1: CGPoint(x: 10.01, y: 85.47), controlPoint2: CGPoint(x: 10.57, y: 85.78))
        bezierPath.addCurve(to: CGPoint(x: 11.31, y: 85.77), controlPoint1: CGPoint(x: 11.22, y: 85.78), controlPoint2: CGPoint(x: 11.26, y: 85.78))
        bezierPath.addCurve(to: CGPoint(x: 26.96, y: 69.36), controlPoint1: CGPoint(x: 21.66, y: 84.95), controlPoint2: CGPoint(x: 26.07, y: 74.67))
        bezierPath.addCurve(to: CGPoint(x: 26.9, y: 68.52), controlPoint1: CGPoint(x: 27.01, y: 69.08), controlPoint2: CGPoint(x: 26.99, y: 68.79))
        bezierPath.addCurve(to: CGPoint(x: 25.1, y: 60.55), controlPoint1: CGPoint(x: 26.09, y: 66.05), controlPoint2: CGPoint(x: 25.51, y: 63.36))
        bezierPath.addCurve(to: CGPoint(x: 44.17, y: 51), controlPoint1: CGPoint(x: 31.07, y: 56.4), controlPoint2: CGPoint(x: 36.65, y: 53.19))
        bezierPath.addCurve(to: CGPoint(x: 46.19, y: 50.42), controlPoint1: CGPoint(x: 44.85, y: 50.8), controlPoint2: CGPoint(x: 45.52, y: 50.61))
        bezierPath.addCurve(to: CGPoint(x: 67.95, y: 68.91), controlPoint1: CGPoint(x: 48.08, y: 51.1), controlPoint2: CGPoint(x: 63.12, y: 56.84))
        bezierPath.addCurve(to: CGPoint(x: 64.91, y: 93.48), controlPoint1: CGPoint(x: 70.82, y: 76.1), controlPoint2: CGPoint(x: 69.8, y: 84.36))
        bezierPath.addCurve(to: CGPoint(x: 48.13, y: 118.78), controlPoint1: CGPoint(x: 59.55, y: 103.47), controlPoint2: CGPoint(x: 53.48, y: 111.6))
        bezierPath.addCurve(to: CGPoint(x: 34.41, y: 141.58), controlPoint1: CGPoint(x: 41.94, y: 127.07), controlPoint2: CGPoint(x: 36.6, y: 134.23))
        bezierPath.addCurve(to: CGPoint(x: 34.59, y: 156.23), controlPoint1: CGPoint(x: 32.93, y: 146.54), controlPoint2: CGPoint(x: 32.97, y: 151.34))
        bezierPath.addCurve(to: CGPoint(x: 11.42, y: 125.74), controlPoint1: CGPoint(x: 25.48, y: 146.79), controlPoint2: CGPoint(x: 17.5, y: 136.37))
        bezierPath.addCurve(to: CGPoint(x: 6, y: 113.52), controlPoint1: CGPoint(x: 9.12, y: 121.71), controlPoint2: CGPoint(x: 7.31, y: 117.61))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: 88.06, y: 72.43))
        bezierPath.addCurve(to: CGPoint(x: 65.42, y: 45.89), controlPoint1: CGPoint(x: 77.94, y: 61.09), controlPoint2: CGPoint(x: 69.16, y: 50.48))
        bezierPath.addCurve(to: CGPoint(x: 141.7, y: 82.27), controlPoint1: CGPoint(x: 97.33, y: 40.24), controlPoint2: CGPoint(x: 121.99, y: 47.02))
        bezierPath.addCurve(to: CGPoint(x: 151.94, y: 177.14), controlPoint1: CGPoint(x: 156.15, y: 108.12), controlPoint2: CGPoint(x: 160.93, y: 152.46))
        bezierPath.addCurve(to: CGPoint(x: 138.75, y: 193.36), controlPoint1: CGPoint(x: 148.85, y: 185.64), controlPoint2: CGPoint(x: 144.29, y: 191.25))
        bezierPath.addCurve(to: CGPoint(x: 71.49, y: 184.88), controlPoint1: CGPoint(x: 114.02, y: 202.79), controlPoint2: CGPoint(x: 89.32, y: 194.67))
        bezierPath.addLine(to: CGPoint(x: 92.23, y: 184.88))
        bezierPath.addCurve(to: CGPoint(x: 93.99, y: 183.12), controlPoint1: CGPoint(x: 93.2, y: 184.88), controlPoint2: CGPoint(x: 93.99, y: 184.09))
        bezierPath.addCurve(to: CGPoint(x: 92.23, y: 181.37), controlPoint1: CGPoint(x: 93.99, y: 182.15), controlPoint2: CGPoint(x: 93.2, y: 181.37))
        bezierPath.addLine(to: CGPoint(x: 65.48, y: 181.37))
        bezierPath.addCurve(to: CGPoint(x: 53.87, y: 173.39), controlPoint1: CGPoint(x: 61.55, y: 178.94), controlPoint2: CGPoint(x: 57.67, y: 176.27))
        bezierPath.addLine(to: CGPoint(x: 68.94, y: 173.39))
        bezierPath.addCurve(to: CGPoint(x: 70.7, y: 171.63), controlPoint1: CGPoint(x: 69.91, y: 173.39), controlPoint2: CGPoint(x: 70.7, y: 172.6))
        bezierPath.addCurve(to: CGPoint(x: 68.94, y: 169.88), controlPoint1: CGPoint(x: 70.7, y: 170.66), controlPoint2: CGPoint(x: 69.91, y: 169.88))
        bezierPath.addLine(to: CGPoint(x: 49.42, y: 169.88))
        bezierPath.addCurve(to: CGPoint(x: 42.65, y: 164.05), controlPoint1: CGPoint(x: 47.12, y: 168), controlPoint2: CGPoint(x: 44.86, y: 166.06))
        bezierPath.addCurve(to: CGPoint(x: 50.95, y: 120.87), controlPoint1: CGPoint(x: 31.11, y: 147.91), controlPoint2: CGPoint(x: 38.93, y: 136.99))
        bezierPath.addCurve(to: CGPoint(x: 68.01, y: 95.14), controlPoint1: CGPoint(x: 56.38, y: 113.6), controlPoint2: CGPoint(x: 62.53, y: 105.36))
        bezierPath.addCurve(to: CGPoint(x: 71.2, y: 67.58), controlPoint1: CGPoint(x: 73.42, y: 85.05), controlPoint2: CGPoint(x: 74.49, y: 75.78))
        bezierPath.addCurve(to: CGPoint(x: 51.74, y: 48.92), controlPoint1: CGPoint(x: 67.09, y: 57.34), controlPoint2: CGPoint(x: 57.28, y: 51.5))
        bezierPath.addCurve(to: CGPoint(x: 61.5, y: 46.64), controlPoint1: CGPoint(x: 55.07, y: 48.05), controlPoint2: CGPoint(x: 58.32, y: 47.29))
        bezierPath.addCurve(to: CGPoint(x: 100.24, y: 90.74), controlPoint1: CGPoint(x: 65.25, y: 51.29), controlPoint2: CGPoint(x: 83.8, y: 74.09))
        bezierPath.addCurve(to: CGPoint(x: 86.43, y: 133.29), controlPoint1: CGPoint(x: 99.55, y: 94.25), controlPoint2: CGPoint(x: 95.05, y: 115.82))
        bezierPath.addLine(to: CGPoint(x: 71.15, y: 137.49))
        bezierPath.addCurve(to: CGPoint(x: 69.92, y: 139.65), controlPoint1: CGPoint(x: 70.21, y: 137.75), controlPoint2: CGPoint(x: 69.66, y: 138.72))
        bezierPath.addCurve(to: CGPoint(x: 71.61, y: 140.94), controlPoint1: CGPoint(x: 70.13, y: 140.43), controlPoint2: CGPoint(x: 70.84, y: 140.94))
        bezierPath.addCurve(to: CGPoint(x: 72.08, y: 140.88), controlPoint1: CGPoint(x: 71.77, y: 140.94), controlPoint2: CGPoint(x: 71.92, y: 140.92))
        bezierPath.addLine(to: CGPoint(x: 84.2, y: 137.55))
        bezierPath.addCurve(to: CGPoint(x: 68.08, y: 154.88), controlPoint1: CGPoint(x: 79.78, y: 145.47), controlPoint2: CGPoint(x: 74.41, y: 152.04))
        bezierPath.addCurve(to: CGPoint(x: 67.2, y: 157.2), controlPoint1: CGPoint(x: 67.2, y: 155.28), controlPoint2: CGPoint(x: 66.8, y: 156.31))
        bezierPath.addCurve(to: CGPoint(x: 68.8, y: 158.23), controlPoint1: CGPoint(x: 67.49, y: 157.85), controlPoint2: CGPoint(x: 68.13, y: 158.23))
        bezierPath.addCurve(to: CGPoint(x: 69.52, y: 158.08), controlPoint1: CGPoint(x: 69.04, y: 158.23), controlPoint2: CGPoint(x: 69.29, y: 158.18))
        bezierPath.addCurve(to: CGPoint(x: 93.97, y: 124.94), controlPoint1: CGPoint(x: 80.38, y: 153.22), controlPoint2: CGPoint(x: 88.42, y: 139.03))
        bezierPath.addLine(to: CGPoint(x: 98.08, y: 136.05))
        bezierPath.addCurve(to: CGPoint(x: 99.73, y: 137.2), controlPoint1: CGPoint(x: 98.34, y: 136.76), controlPoint2: CGPoint(x: 99.01, y: 137.2))
        bezierPath.addCurve(to: CGPoint(x: 100.33, y: 137.09), controlPoint1: CGPoint(x: 99.93, y: 137.2), controlPoint2: CGPoint(x: 100.13, y: 137.16))
        bezierPath.addCurve(to: CGPoint(x: 101.38, y: 134.84), controlPoint1: CGPoint(x: 101.24, y: 136.76), controlPoint2: CGPoint(x: 101.71, y: 135.75))
        bezierPath.addLine(to: CGPoint(x: 95.86, y: 119.9))
        bezierPath.addCurve(to: CGPoint(x: 103.23, y: 93.72), controlPoint1: CGPoint(x: 99.8, y: 108.85), controlPoint2: CGPoint(x: 102.2, y: 98.56))
        bezierPath.addCurve(to: CGPoint(x: 118.34, y: 106.51), controlPoint1: CGPoint(x: 108.9, y: 99.28), controlPoint2: CGPoint(x: 114.18, y: 103.89))
        bezierPath.addLine(to: CGPoint(x: 120.49, y: 117.1))
        bezierPath.addCurve(to: CGPoint(x: 122.21, y: 118.5), controlPoint1: CGPoint(x: 120.66, y: 117.93), controlPoint2: CGPoint(x: 121.39, y: 118.5))
        bezierPath.addCurve(to: CGPoint(x: 122.57, y: 118.47), controlPoint1: CGPoint(x: 122.33, y: 118.5), controlPoint2: CGPoint(x: 122.45, y: 118.49))
        bezierPath.addCurve(to: CGPoint(x: 123.94, y: 116.4), controlPoint1: CGPoint(x: 123.52, y: 118.27), controlPoint2: CGPoint(x: 124.13, y: 117.35))
        bezierPath.addLine(to: CGPoint(x: 122, y: 106.85))
        bezierPath.addLine(to: CGPoint(x: 136.56, y: 104.45))
        bezierPath.addCurve(to: CGPoint(x: 138.01, y: 102.44), controlPoint1: CGPoint(x: 137.52, y: 104.3), controlPoint2: CGPoint(x: 138.16, y: 103.39))
        bezierPath.addCurve(to: CGPoint(x: 135.99, y: 100.99), controlPoint1: CGPoint(x: 137.85, y: 101.48), controlPoint2: CGPoint(x: 136.94, y: 100.83))
        bezierPath.addLine(to: CGPoint(x: 120.27, y: 103.57))
        bezierPath.addCurve(to: CGPoint(x: 91.27, y: 76.07), controlPoint1: CGPoint(x: 113, y: 99.04), controlPoint2: CGPoint(x: 101.8, y: 87.69))
        bezierPath.addLine(to: CGPoint(x: 122.58, y: 77.83))
        bezierPath.addCurve(to: CGPoint(x: 122.69, y: 77.83), controlPoint1: CGPoint(x: 122.62, y: 77.83), controlPoint2: CGPoint(x: 122.65, y: 77.83))
        bezierPath.addCurve(to: CGPoint(x: 124.44, y: 76.18), controlPoint1: CGPoint(x: 123.61, y: 77.83), controlPoint2: CGPoint(x: 124.39, y: 77.11))
        bezierPath.addCurve(to: CGPoint(x: 122.78, y: 74.33), controlPoint1: CGPoint(x: 124.49, y: 75.21), controlPoint2: CGPoint(x: 123.75, y: 74.38))
        bezierPath.addLine(to: CGPoint(x: 118.33, y: 74.08))
        bezierPath.addLine(to: CGPoint(x: 122.06, y: 70.3))
        bezierPath.addCurve(to: CGPoint(x: 122.04, y: 67.82), controlPoint1: CGPoint(x: 122.74, y: 69.61), controlPoint2: CGPoint(x: 122.74, y: 68.5))
        bezierPath.addCurve(to: CGPoint(x: 119.56, y: 67.84), controlPoint1: CGPoint(x: 121.35, y: 67.14), controlPoint2: CGPoint(x: 120.24, y: 67.15))
        bezierPath.addLine(to: CGPoint(x: 113.65, y: 73.81))
        bezierPath.addLine(to: CGPoint(x: 88.06, y: 72.46))
        bezierPath.addLine(to: CGPoint(x: 88.06, y: 72.43))
        bezierPath.close()
        fillColor.setFill()
        bezierPath.fill()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 146.44, y: 142.57))
        bezier2Path.addCurve(to: CGPoint(x: 146.43, y: 142.57), controlPoint1: CGPoint(x: 146.44, y: 142.57), controlPoint2: CGPoint(x: 146.44, y: 142.57))
        bezier2Path.addCurve(to: CGPoint(x: 144.68, y: 144.33), controlPoint1: CGPoint(x: 145.46, y: 142.57), controlPoint2: CGPoint(x: 144.68, y: 143.36))
        bezier2Path.addCurve(to: CGPoint(x: 129.61, y: 185.13), controlPoint1: CGPoint(x: 144.77, y: 165.92), controlPoint2: CGPoint(x: 139, y: 181.55))
        bezier2Path.addCurve(to: CGPoint(x: 128.6, y: 187.4), controlPoint1: CGPoint(x: 128.7, y: 185.48), controlPoint2: CGPoint(x: 128.25, y: 186.49))
        bezier2Path.addCurve(to: CGPoint(x: 130.24, y: 188.52), controlPoint1: CGPoint(x: 128.86, y: 188.1), controlPoint2: CGPoint(x: 129.53, y: 188.52))
        bezier2Path.addCurve(to: CGPoint(x: 130.87, y: 188.41), controlPoint1: CGPoint(x: 130.45, y: 188.52), controlPoint2: CGPoint(x: 130.66, y: 188.49))
        bezier2Path.addCurve(to: CGPoint(x: 148.2, y: 144.32), controlPoint1: CGPoint(x: 141.81, y: 184.23), controlPoint2: CGPoint(x: 148.29, y: 167.75))
        bezier2Path.addCurve(to: CGPoint(x: 146.44, y: 142.57), controlPoint1: CGPoint(x: 148.2, y: 143.35), controlPoint2: CGPoint(x: 147.41, y: 142.57))
        bezier2Path.close()
        fillColor.setFill()
        bezier2Path.fill()
        
        context.restoreGState()

    }




    @objc(HeartResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
